# Generated by Django 5.0.4 on 2024-05-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_attention', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeattention',
            options={'verbose_name_plural': 'types_attention'},
        ),
        migrations.AlterModelTable(
            name='typeattention',
            table='type_attention',
        ),
    ]
