# Generated by Django 5.0.4 on 2024-05-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_attention', '0002_alter_typeattention_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='typeattention',
            table='types_attention',
        ),
    ]
