# Generated by Django 5.0.4 on 2024-05-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petowner',
            options={'verbose_name_plural': 'pets_owner'},
        ),
        migrations.AlterModelTable(
            name='petowner',
            table='pet_owner',
        ),
    ]
