# Generated by Django 5.0.4 on 2024-05-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_owner', '0002_alter_petowner_options_alter_petowner_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='petowner',
            table='pets_owner',
        ),
    ]
