# Generated by Django 5.0.4 on 2024-05-09 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turn', '0003_alter_turn_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('id_turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turn.turn')),
            ],
            options={
                'verbose_name_plural': 'schedules',
                'db_table': 'schedules',
            },
        ),
    ]
