# Generated by Django 5.0.4 on 2024-06-21 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type_attention', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_professional', models.CharField(max_length=50)),
                ('last_name_professional', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=20)),
                ('type_attention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type_attention.typeattention')),
            ],
            options={
                'verbose_name_plural': 'professionals',
                'db_table': 'professional',
            },
        ),
    ]
