# Generated by Django 5.0.4 on 2024-11-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='image_professional',
            field=models.ImageField(null=True, upload_to='professionals'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='registration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
