# Generated by Django 5.0.4 on 2024-11-10 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_professional_image_professional_and_more'),
        ('type_attention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='first_name_professional',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='image_professional',
            field=models.ImageField(upload_to='professionals'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='last_name_professional',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='professional',
            name='registration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='professional',
            name='type_attention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='type_attention.typeattention'),
        ),
    ]
