# Generated by Django 5.0.4 on 2024-11-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_alter_professional_first_name_professional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='image_professional',
            field=models.ImageField(blank=True, null=True, upload_to='professionals'),
        ),
    ]
