# Generated by Django 5.0.4 on 2024-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_pet_name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'types_pet',
                'db_table': 'types_pet',
            },
        ),
    ]
