# Generated by Django 5.0.4 on 2024-05-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_breed', models.CharField(max_length=50, verbose_name='name_breed')),
            ],
            options={
                'verbose_name_plural': 'pets_breed',
                'db_table': 'pets_breed',
            },
        ),
    ]
