# Generated by Django 5.0.4 on 2024-05-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0002_alter_turn_options_alter_turn_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='turn',
            table='turns',
        ),
    ]
