# Generated by Django 5.0.4 on 2024-05-09 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_breed', '0001_initial'),
        ('pet_owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('date_birth_pet', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('id_pet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_breed.petbreed')),
                ('id_pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_owner.petowner')),
            ],
        ),
    ]
