# Generated by Django 5.0.4 on 2024-11-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_pet',
            field=models.ImageField(null=True, upload_to='pets'),
        ),
    ]
