# Generated by Django 5.0.4 on 2024-11-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_image_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_pet',
            field=models.ImageField(blank=True, null=True, upload_to='pets'),
        ),
    ]
